# GENERATED by tools/gen_bridge_expectations.py — do not edit.
#
# Expected bridge surface, derived from include/dopewars.h. Regenerate with
#   task gen:bridge-expectations
# and note that task bridge:test fails if this file is stale with respect to
# the header, so an edit here without a header change is caught, and a header
# change without a regeneration is caught too.

class_name BridgeExpectations

## Every pointer-free ABI declaration the shim forwards, as the
## GDScript-side method name plus the value the ABI contract pins for it.
## Only pointer-free no-argument functions appear here because this table
## drives value and width-fidelity checks via a zero-arg call. The
## pointer-argument side of the ABI is forwarded by the shim and covered
## behaviourally by res://tests/test_bridge.gd and the Tier-C suites.

# method name -> { "value": pinned value, "c_type": C return type,
#                          "width": "uint32" | "int32" | "int64" | "size" }
#
# Untyped on purpose: Godot 4.7 rejects a nested typed collection
# (Dictionary[String, Dictionary[...]]) as a const type, and the shape is
# validated by the test at load time, so a malformed table is a test failure
# rather than a script parse error.
const ABI = {
	"abi_version": {"c_type": "uint32_t", "width": "uint32"},
	"rules_default_num_days": {"value": 31, "c_type": "uint32_t", "width": "uint32"},
	"rules_default_start_cash": {"value": 2000, "c_type": "int32_t", "width": "int32"},
	"rules_default_start_debt": {"value": 5500, "c_type": "int64_t", "width": "int64"},
	"rules_default_start_health": {"value": 100, "c_type": "int32_t", "width": "int32"},
	"rules_default_start_coat_capacity": {"value": 100, "c_type": "int32_t", "width": "int32"},
	"rules_default_start_location_index": {"value": 0, "c_type": "int32_t", "width": "int32"},
	"rules_gun_damage": {"value": 5, "c_type": "uint32_t", "width": "uint32"},
	"rules_gun_space": {"value": 4, "c_type": "uint32_t", "width": "uint32"},
	"rules_player_armor": {"value": 100, "c_type": "uint32_t", "width": "uint32"},
	"rules_debt_interest_bp": {"value": 1000, "c_type": "uint32_t", "width": "uint32"},
	"rules_bank_interest_bp": {"value": 500, "c_type": "uint32_t", "width": "uint32"},
	"rules_bank_purchase_fee_bp": {"value": 2500, "c_type": "uint32_t", "width": "uint32"},
	"rules_cheap_divide": {"value": 10, "c_type": "uint32_t", "width": "uint32"},
	"rules_expensive_multiply": {"value": 5, "c_type": "uint32_t", "width": "uint32"},
	"rules_locations_len": {"value": 6, "c_type": "uint32_t", "width": "uint32"},
	"rules_drugs_len": {"value": 12, "c_type": "uint32_t", "width": "uint32"},
	"world_size": {"c_type": "size_t", "width": "size"},
	"world_align": {"c_type": "size_t", "width": "size"},
	"world_dump_len": {"c_type": "size_t", "width": "size"},
}

# ABI identity, read from the header's DW_ABI_VERSION #define. Not a copy:
# a bump to the header moves this, and a shim still reporting the old value
# fails the bridge test.
const DW_ABI_VERSION: int = 3

